GET http://localhost:1000/api/recipes/64d6358358eb56e7fb61fce

###

DELETE http://localhost:1000/api/recipes/64d543e5193d030e99fddb2b
###

GET http://localhost:1000/api/recipes

###

GET http://localhost:1000/api/quotes

###

POST http://localhost:1000/api/recipes
Content-Type: application/json

{
    "name": "Michito",
    "ingredients": ["un Micho", "Un Dan"],
    "instructions": ["un dan", "un micho"],
    "category": "micho",
    "image": "lalal"
}